ROOT := ../../../

CPP_SOURCES := \
   sxcompr.cpp \
   sxcrypt.cpp \
   sxdate.cpp \
   sxsem.cpp \
   sxfname.cpp \
   sxtable.cpp \
   sxord.cpp \
   sxutil.cpp \
   sxredir.cpp \

PRG_SOURCES := \
   sxcompat.prg \
   sxini.prg \
   sxtrig.prg \

LIBNAME := hbsix

HB_CFLAGS += -D_HB_API_INTERNAL_

include $(TOP)$(ROOT)config/lib.mk
