ROOT := ../../

include $(TOP)$(ROOT)config/global.mk

HB_PRGFLAGS += -w3 -gc3

CPP_SOURCES := \
   bcrypt.cpp \
   commctrl.cpp \
   errhandlingapi.cpp \
   libloaderapi.cpp \
   mmsystem.cpp \
   sysinfoapi.cpp \
   utils.cpp \
   winbase.cpp \
   wingdi.cpp \
   winhttp.cpp \
   winnetwk.cpp \
   winnls.cpp \
   winreg.cpp \
   winspool.cpp \
   winuser.cpp \
   winver.cpp \
   gdiplusflat.cpp \
   gdiplusinit.cpp \
   gl.cpp \

PRG_SOURCES := \
   struct_abc.prg \
   struct_abcfloat.prg \
   struct_accel.prg \
   struct_bitmap.prg \
   struct_bitmapinfo.prg \
   struct_bitmapinfoheader.prg \
   struct_blendfunction.prg \
   struct_capdrivercaps.prg \
   struct_coloradjustment.prg \
   struct_colormap.prg \
   struct_comboboxinfo.prg \
   struct_compareitemstruct.prg \
   struct_comstat.prg \
   struct_cursorinfo.prg \
   struct_dcb.prg \
   struct_deleteitemstruct.prg \
   struct_drawitemstruct.prg \
   struct_drawtextparams.prg \
   struct_filetime.prg \
   struct_flashwinfo.prg \
   struct_gradient_rect.prg \
   struct_gradient_triangle.prg \
   struct_iconinfo.prg \
   struct_imageinfo.prg \
   struct_imagelistdrawparams.prg \
   struct_initcommoncontrolsex.prg \
   struct_kerningpair.prg \
   struct_logbrush.prg \
   struct_logpalette.prg \
   struct_logpen.prg \
   struct_measureitemstruct.prg \
   struct_memorystatusex.prg \
   struct_menubarinfo.prg \
   struct_menuinfo.prg \
   struct_monitorinfo.prg \
   struct_mousemovepoint.prg \
   struct_msg.prg \
   struct_nmhdr.prg \
   struct_paintstruct.prg \
   struct_paletteentry.prg \
   struct_pixelformatdescriptor.prg \
   struct_point.prg \
   struct_pointf.prg \
   struct_pointfloat.prg \
   struct_rect.prg \
   struct_rgbquad.prg \
   struct_scrollbarinfo.prg \
   struct_scrollinfo.prg \
   struct_security_attributes.prg \
   struct_size.prg \
   struct_system_info.prg \
   struct_systemtime.prg \
   struct_timecaps.prg \
   struct_titlebarinfo.prg \
   struct_trackmouseevent.prg \
   struct_trivertex.prg \
   struct_updatelayeredwindowinfo.prg \
   struct_windowinfo.prg \
   struct_windowplacement.prg \
   struct_windowpos.prg \
   struct_wndclass.prg \
   struct_wndclassex.prg \
   struct_xform.prg \
   gppoint.prg \
   gppointf.prg \
   gprect.prg \
   gprectf.prg \
   gpsize.prg \
   gpsizef.prg \

LIBNAME := hbwinapi

DIRS =

include $(TOP)$(ROOT)config/lib.mk
include $(TOP)$(ROOT)config/dir.mk
