ROOT := ../../

#YACC_FLAGS := -p hb_comp
YACC_SOURCE := harbour.y
YACC_DEPEND := complex.cpp
YACC_HEADERS := \
   hbcomp.h \
   hbcompdf.h \
   hbsetup.h \
   hbpcode.h \
   hbdefs.h \
   hberrors.h \
   hbpp.h \

CPP_SOURCES := \
   cmdcheck.cpp \
   compi18n.cpp \
   complex.cpp \
   expropta.cpp \
   exproptb.cpp \
   genc.cpp \
   gencc.cpp \
   genhrb.cpp \
   hbcmplib.cpp \
   hbcomp.cpp \
   hbdbginf.cpp \
   hbdead.cpp \
   hbfix.cpp \
   hbfunchk.cpp \
   hbgenerr.cpp \
   hbident.cpp \
   hblbl.cpp \
   hbmain.cpp \
   hbopt.cpp \
   hbpcode.cpp \
   hbstripl.cpp \
   hbusage.cpp \
   ppcomp.cpp \

LIBNAME := hbcplr

include $(TOP)$(ROOT)config/lib.mk
