ROOT := ../../

#YACC_FLAGS := -p hb_macro
YACC_SOURCE := macro.y
YACC_DEPEND := macrolex.cpp
YACC_HEADERS := \
   hbmacro.h \
   hbsetup.h \
   hbpcode.h \
   hbdefs.h \

CPP_SOURCES := \
   macroa.cpp \
   macrob.cpp \
   macrolex.cpp \

LIBNAME := hbmacro

include $(TOP)$(ROOT)config/lib.mk
