/*
 * WinApi test
 *
 * Copyright 2022 Marcos Antonio Gambeta <marcosgambeta AT outlook DOT com>
 *
 */

#include "winapi_winuser.ch"

PROCEDURE Main()

   ? "SM_CXSCREEN...................=", WinApi_GetSystemMetrics(SM_CXSCREEN)
   ? "SM_CYSCREEN...................=", WinApi_GetSystemMetrics(SM_CYSCREEN)
   ? "SM_CXVSCROLL..................=", WinApi_GetSystemMetrics(SM_CXVSCROLL)
   ? "SM_CYHSCROLL..................=", WinApi_GetSystemMetrics(SM_CYHSCROLL)
   ? "SM_CYCAPTION..................=", WinApi_GetSystemMetrics(SM_CYCAPTION)
   ? "SM_CXBORDER...................=", WinApi_GetSystemMetrics(SM_CXBORDER)
   ? "SM_CYBORDER...................=", WinApi_GetSystemMetrics(SM_CYBORDER)
   ? "SM_CXDLGFRAME.................=", WinApi_GetSystemMetrics(SM_CXDLGFRAME)
   ? "SM_CYDLGFRAME.................=", WinApi_GetSystemMetrics(SM_CYDLGFRAME)
   ? "SM_CYVTHUMB...................=", WinApi_GetSystemMetrics(SM_CYVTHUMB)
   ? "SM_CXHTHUMB...................=", WinApi_GetSystemMetrics(SM_CXHTHUMB)
   ? "SM_CXICON.....................=", WinApi_GetSystemMetrics(SM_CXICON)
   ? "SM_CYICON.....................=", WinApi_GetSystemMetrics(SM_CYICON)
   ? "SM_CXCURSOR...................=", WinApi_GetSystemMetrics(SM_CXCURSOR)
   ? "SM_CYCURSOR...................=", WinApi_GetSystemMetrics(SM_CYCURSOR)
   ? "SM_CYMENU.....................=", WinApi_GetSystemMetrics(SM_CYMENU)
   ? "SM_CXFULLSCREEN...............=", WinApi_GetSystemMetrics(SM_CXFULLSCREEN)
   ? "SM_CYFULLSCREEN...............=", WinApi_GetSystemMetrics(SM_CYFULLSCREEN)
   ? "SM_CYKANJIWINDOW..............=", WinApi_GetSystemMetrics(SM_CYKANJIWINDOW)
   ? "SM_MOUSEPRESENT...............=", WinApi_GetSystemMetrics(SM_MOUSEPRESENT)
   ? "SM_CYVSCROLL..................=", WinApi_GetSystemMetrics(SM_CYVSCROLL)
   ? "SM_CXHSCROLL..................=", WinApi_GetSystemMetrics(SM_CXHSCROLL)
   ? "SM_DEBUG......................=", WinApi_GetSystemMetrics(SM_DEBUG)
   ? "SM_SWAPBUTTON.................=", WinApi_GetSystemMetrics(SM_SWAPBUTTON)
   ? "SM_RESERVED1..................=", WinApi_GetSystemMetrics(SM_RESERVED1)
   ? "SM_RESERVED2..................=", WinApi_GetSystemMetrics(SM_RESERVED2)
   ? "SM_RESERVED3..................=", WinApi_GetSystemMetrics(SM_RESERVED3)
   ? "SM_RESERVED4..................=", WinApi_GetSystemMetrics(SM_RESERVED4)
   ? "SM_CXMIN......................=", WinApi_GetSystemMetrics(SM_CXMIN)
   ? "SM_CYMIN......................=", WinApi_GetSystemMetrics(SM_CYMIN)
   ? "SM_CXSIZE.....................=", WinApi_GetSystemMetrics(SM_CXSIZE)
   ? "SM_CYSIZE.....................=", WinApi_GetSystemMetrics(SM_CYSIZE)
   ? "SM_CXFRAME....................=", WinApi_GetSystemMetrics(SM_CXFRAME)
   ? "SM_CYFRAME....................=", WinApi_GetSystemMetrics(SM_CYFRAME)
   ? "SM_CXMINTRACK.................=", WinApi_GetSystemMetrics(SM_CXMINTRACK)
   ? "SM_CYMINTRACK.................=", WinApi_GetSystemMetrics(SM_CYMINTRACK)
   ? "SM_CXDOUBLECLK................=", WinApi_GetSystemMetrics(SM_CXDOUBLECLK)
   ? "SM_CYDOUBLECLK................=", WinApi_GetSystemMetrics(SM_CYDOUBLECLK)
   ? "SM_CXICONSPACING..............=", WinApi_GetSystemMetrics(SM_CXICONSPACING)
   ? "SM_CYICONSPACING..............=", WinApi_GetSystemMetrics(SM_CYICONSPACING)
   ? "SM_MENUDROPALIGNMENT..........=", WinApi_GetSystemMetrics(SM_MENUDROPALIGNMENT)
   ? "SM_PENWINDOWS.................=", WinApi_GetSystemMetrics(SM_PENWINDOWS)
   ? "SM_DBCSENABLED................=", WinApi_GetSystemMetrics(SM_DBCSENABLED)
   ? "SM_CMOUSEBUTTONS..............=", WinApi_GetSystemMetrics(SM_CMOUSEBUTTONS)
   ? "SM_CXFIXEDFRAME...............=", WinApi_GetSystemMetrics(SM_CXFIXEDFRAME)
   ? "SM_CYFIXEDFRAME...............=", WinApi_GetSystemMetrics(SM_CYFIXEDFRAME)
   ? "SM_CXSIZEFRAME................=", WinApi_GetSystemMetrics(SM_CXSIZEFRAME)
   ? "SM_CYSIZEFRAME................=", WinApi_GetSystemMetrics(SM_CYSIZEFRAME)
   ? "SM_SECURE.....................=", WinApi_GetSystemMetrics(SM_SECURE)
   ? "SM_CXEDGE.....................=", WinApi_GetSystemMetrics(SM_CXEDGE)
   ? "SM_CYEDGE.....................=", WinApi_GetSystemMetrics(SM_CYEDGE)
   ? "SM_CXMINSPACING...............=", WinApi_GetSystemMetrics(SM_CXMINSPACING)
   ? "SM_CYMINSPACING...............=", WinApi_GetSystemMetrics(SM_CYMINSPACING)
   ? "SM_CXSMICON...................=", WinApi_GetSystemMetrics(SM_CXSMICON)
   ? "SM_CYSMICON...................=", WinApi_GetSystemMetrics(SM_CYSMICON)
   ? "SM_CYSMCAPTION................=", WinApi_GetSystemMetrics(SM_CYSMCAPTION)
   ? "SM_CXSMSIZE...................=", WinApi_GetSystemMetrics(SM_CXSMSIZE)
   ? "SM_CYSMSIZE...................=", WinApi_GetSystemMetrics(SM_CYSMSIZE)
   ? "SM_CXMENUSIZE.................=", WinApi_GetSystemMetrics(SM_CXMENUSIZE)
   ? "SM_CYMENUSIZE.................=", WinApi_GetSystemMetrics(SM_CYMENUSIZE)
   ? "SM_ARRANGE....................=", WinApi_GetSystemMetrics(SM_ARRANGE)
   ? "SM_CXMINIMIZED................=", WinApi_GetSystemMetrics(SM_CXMINIMIZED)
   ? "SM_CYMINIMIZED................=", WinApi_GetSystemMetrics(SM_CYMINIMIZED)
   ? "SM_CXMAXTRACK.................=", WinApi_GetSystemMetrics(SM_CXMAXTRACK)
   ? "SM_CYMAXTRACK.................=", WinApi_GetSystemMetrics(SM_CYMAXTRACK)
   ? "SM_CXMAXIMIZED................=", WinApi_GetSystemMetrics(SM_CXMAXIMIZED)
   ? "SM_CYMAXIMIZED................=", WinApi_GetSystemMetrics(SM_CYMAXIMIZED)
   ? "SM_NETWORK....................=", WinApi_GetSystemMetrics(SM_NETWORK)
   ? "SM_CLEANBOOT..................=", WinApi_GetSystemMetrics(SM_CLEANBOOT)
   ? "SM_CXDRAG.....................=", WinApi_GetSystemMetrics(SM_CXDRAG)
   ? "SM_CYDRAG.....................=", WinApi_GetSystemMetrics(SM_CYDRAG)
   ? "SM_SHOWSOUNDS.................=", WinApi_GetSystemMetrics(SM_SHOWSOUNDS)
   ? "SM_CXMENUCHECK................=", WinApi_GetSystemMetrics(SM_CXMENUCHECK)
   ? "SM_CYMENUCHECK................=", WinApi_GetSystemMetrics(SM_CYMENUCHECK)
   ? "SM_SLOWMACHINE................=", WinApi_GetSystemMetrics(SM_SLOWMACHINE)
   ? "SM_MIDEASTENABLED.............=", WinApi_GetSystemMetrics(SM_MIDEASTENABLED)
   ? "SM_MOUSEWHEELPRESENT..........=", WinApi_GetSystemMetrics(SM_MOUSEWHEELPRESENT)
   ? "SM_XVIRTUALSCREEN.............=", WinApi_GetSystemMetrics(SM_XVIRTUALSCREEN)
   ? "SM_YVIRTUALSCREEN.............=", WinApi_GetSystemMetrics(SM_YVIRTUALSCREEN)
   ? "SM_CXVIRTUALSCREEN............=", WinApi_GetSystemMetrics(SM_CXVIRTUALSCREEN)
   ? "SM_CYVIRTUALSCREEN............=", WinApi_GetSystemMetrics(SM_CYVIRTUALSCREEN)
   ? "SM_CMONITORS..................=", WinApi_GetSystemMetrics(SM_CMONITORS)
   ? "SM_SAMEDISPLAYFORMAT..........=", WinApi_GetSystemMetrics(SM_SAMEDISPLAYFORMAT)
   ? "SM_IMMENABLED.................=", WinApi_GetSystemMetrics(SM_IMMENABLED)
   ? "SM_CXFOCUSBORDER..............=", WinApi_GetSystemMetrics(SM_CXFOCUSBORDER)
   ? "SM_CYFOCUSBORDER..............=", WinApi_GetSystemMetrics(SM_CYFOCUSBORDER)
   ? "SM_TABLETPC...................=", WinApi_GetSystemMetrics(SM_TABLETPC)
   ? "SM_MEDIACENTER................=", WinApi_GetSystemMetrics(SM_MEDIACENTER)
   ? "SM_STARTER....................=", WinApi_GetSystemMetrics(SM_STARTER)
   ? "SM_SERVERR2...................=", WinApi_GetSystemMetrics(SM_SERVERR2)
   ? "SM_MOUSEHORIZONTALWHEELPRESENT=", WinApi_GetSystemMetrics(SM_MOUSEHORIZONTALWHEELPRESENT)
   ? "SM_CXPADDEDBORDER.............=", WinApi_GetSystemMetrics(SM_CXPADDEDBORDER)
   ? "SM_DIGITIZER..................=", WinApi_GetSystemMetrics(SM_DIGITIZER)
   ? "SM_MAXIMUMTOUCHES.............=", WinApi_GetSystemMetrics(SM_MAXIMUMTOUCHES)
   // ? "SM_CMETRICS...................=", WinApi_GetSystemMetrics(SM_CMETRICS)
   ? "SM_REMOTESESSION..............=", WinApi_GetSystemMetrics(SM_REMOTESESSION)
   ? "SM_SHUTTINGDOWN...............=", WinApi_GetSystemMetrics(SM_SHUTTINGDOWN)
   ? "SM_REMOTECONTROL..............=", WinApi_GetSystemMetrics(SM_REMOTECONTROL)
   ? "SM_CARETBLINKINGENABLED.......=", WinApi_GetSystemMetrics(SM_CARETBLINKINGENABLED)
   ? "SM_CONVERTIBLESLATEMODE.......=", WinApi_GetSystemMetrics(SM_CONVERTIBLESLATEMODE)
   ? "SM_SYSTEMDOCKED...............=", WinApi_GetSystemMetrics(SM_SYSTEMDOCKED)

RETURN
