ROOT := ../../

CPP_SOURCES := \
   expropt1.cpp \
   expropt2.cpp \
   funcid.cpp \
   hbarch.cpp \
   hbdate.cpp \
   hbffind.cpp \
   hbfopen.cpp \
   hbfsapi.cpp \
   hbgete.cpp \
   hbhash.cpp \
   hbmem.cpp \
   hbprintf.cpp \
   hbstr.cpp \
   hbstrbm.cpp \
   hbtrace.cpp \
   hbver.cpp \
   hbverdsp.cpp \
   hbwin.cpp \
   strwild.cpp \

LIBNAME := hbcommon

include $(TOP)$(ROOT)config/lib.mk
