ROOT := ../../

CPP_SOURCES := \
   l_be.cpp \
   l_bg.cpp \
   l_ca.cpp \
   l_cs.cpp \
   l_de.cpp \
   l_de_at.cpp \
   l_ee.cpp \
   l_el.cpp \
   l_eo.cpp \
   l_es.cpp \
   l_es_419.cpp \
   l_eu.cpp \
   l_fr.cpp \
   l_gl.cpp \
   l_he.cpp \
   l_hr.cpp \
   l_hu.cpp \
   l_id.cpp \
   l_is.cpp \
   l_it.cpp \
   l_ko.cpp \
   l_lt.cpp \
   l_lv.cpp \
   l_nl.cpp \
   l_pl.cpp \
   l_pt.cpp \
   l_pt_br.cpp \
   l_ro.cpp \
   l_ru.cpp \
   l_sk.cpp \
   l_sl.cpp \
   l_sr_cyr.cpp \
   l_sr_lat.cpp \
   l_sv.cpp \
   l_tr.cpp \
   l_uk.cpp \
   l_zh.cpp \
   l_zh_sim.cpp \

LIBNAME := hblang

include $(TOP)$(ROOT)config/lib.mk
